version: '3.8'  # Adjust the version as per your Docker Compose compatibility

services:
  catalogdb:
    container_name: catalogdb
    environment:
      POSTGRES_USER: siamese
      POSTGRES_PASSWORD: siamese
      POSTGRES_DB: catalogdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - catalogdb_volume:/var/lib/postgresql/data

  basketdb:
    container_name: basketdb
    environment:
       POSTGRES_USER: siamese
       POSTGRES_PASSWORD: siamese
       POSTGRES_DB: basketdb
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - basketdb_volume:/var/lib/postgresql/data




  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
    - "6379:6379"


  catalog.api:
    container_name: catalog-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORT: 8080
      ASPNETCORE_HTTPS_PORT: 8081
      ConnectionStrings__Database: Server=catalogdb;Port=5432;Database=catalogdb;User Id=siamese;Password=siamese;
      ASPNETCORE_Kestrel__Certificates__Default__Password: 123456
      ASPNETCORE_Kestrel__Certificates__Default__Path: /home/app/.aspnet/https/aspnetapp.pfx
    depends_on:
      - catalogdb
      - basketdb
    ports:
      - "6000:8080"
      - "6050:8081"
    volumes:
    - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
    - ~/.aspnet/https:/home/app/.aspnet/https:ro


  basket.api:
    container_name: basket-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORT: 8080
      ASPNETCORE_HTTPS_PORT: 8081
      ConnectionStrings__Database: Server=basketdb;Port=5432;Database=basketdb;User Id=siamese;Password=siamese;
      ASPNETCORE_Kestrel__Certificates__Default__Password: 123456
      ASPNETCORE_Kestrel__Certificates__Default__Path: /home/app/.aspnet/https/aspnetapp.pfx
    depends_on:
      - basketdb
      - distributedcache
    ports:
      - "6001:8080"
      - "6051:8081"
    volumes:
    - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
    - ~/.aspnet/https:/home/app/.aspnet/https:ro
 
  discount.grpc:
    container_name: discount-grpc
 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORT: 8080
      ASPNETCORE_HTTPS_PORT: 8081
      ConnectionStrings__Database: Data Source=/data/db/discountdb.db; 
      ASPNETCORE_Kestrel__Certificates__Default__Password: 123456
      ASPNETCORE_Kestrel__Certificates__Default__Path: /home/app/.aspnet/https/aspnetapp.pfx
    ports:
      - "6002:8080"
      - "6052:8081"
    volumes:
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro
      - ./data/db:/data/db
      

volumes:
  catalogdb_volume:
  basketdb_volume:
  distributedcache_volume:

