version: '3.8'  # Adjust the version as per your Docker Compose compatibility

services:
  catalogdb:
    container_name: catalogdb
    environment:
      POSTGRES_USER: siamese
      POSTGRES_PASSWORD: siamese
      POSTGRES_DB: catalogdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - catalogdb_volume:/var/lib/postgresql/data

  catalog.api:
    container_name: catalog-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORT: 8080
      ASPNETCORE_HTTPS_PORT: 8081
      ConnectionStrings__Database: Server=catalogdb;Port=5432;Database=catalogdb;User Id=siamese;Password=siamese;
      ASPNETCORE_Kestrel__Certificates__Default__Password: 123456
      ASPNETCORE_Kestrel__Certificates__Default__Path: /home/app/.aspnet/https/aspnetapp.pfx
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6050:8081"
    volumes:
    - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
    - ~/.aspnet/https:/home/app/.aspnet/https:ro
 

volumes:
  catalogdb_volume:
