version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=catalogdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - catalogdb_volume:/var/lib/postgresql/data

volumes:
  catalogdb_volume:
